name: Docker Build and Push

on:
  push:
    branches:
      - staging  # Change to the branch you want to trigger the action on

jobs:
  build_and_push:
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u mohwildanwildan15@gmail.com -p dckr_pat_IhSXIUa-8qUHrSbPdTvX-HVgFNo

      - name: Build and tag the Docker image
        run: docker build -t wildan121/test:${{ github.sha }} .

      - name: Push the Docker image to Docker Hub
        run: docker push wildan121/test:${{ github.sha }}

