name: CI
on: 
  push: 
    branches: ["staging"]

jobs:
  build:
    environment: staging
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3

      - name: Conect To Docker HUB
        uses: docker/login-action@v2
        with: 
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_TOKEN}}

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build And Push
        uses: docker/build-push-action@v4
        with: 
          file: ./Dockerfile
          push: true
          tags: wildan121/test:${{github.sha}}

  deployment:
    needs: build
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - name: Deploy To VPS
        uses: appleboy/ssh-action@master
        env:
          IMAGE_TAG: ${{ github.sha }}
        with:
          host: ${{secrets.SERVER}}
          username: ${{secrets.SERVER_USERNAME}}
          key: ${{secrets.SERVER_SHH_KEY}}
          passphrase: wildan121
          envs: IMAGE_TAG
          script: |
            echo $IMAGE_TAG
            cd ~/app/test && git switch staging
            git pull 
            docker compose down
            docker compose create 
            docker compose start


