name: CI
on: 
  push: 
    branches: ["staging"]

jobs:
  build:
    environment: staging
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3

      - name: Conect To Docker HUB
        uses: docker/login-action@v2
        with: 
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_TOKEN}}

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build And Push
        uses: docker/build-push-action@v4
        with: 
          file: ./Dockerfile
          path: true
          tags: ${{secrets.DOCKER_USERNAME}}/test:latest

  deployment:
    needs: build
    environment: staging
    runs-on: ubuntu-latest
    steps: 
      - name: Deploy To VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SERVER}}
          username: ${{secrets.SERVER_USERNAME}}
          password: ${{secrets.SERVER_PASSWORD}}
          port: ${{secrets.SERVER_PORT}}
          scripts: |
            whoami
            docker stop test || true && docker rm test || true
            docker pull ${{vars.IMAGE_NAME}}
            docker run -d -p 3002:3002 --name ${{vars.CONTAINER_NAME}} ${{vars.IMAGE_NAME}}


