name: Docker Build and Push

on:
  push:
    branches:
      - staging  # Change to the branch you want to trigger the action on

jobs:
  build_and_push:
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u mohwildanwildan15@gmail.com -p dckr_pat_IhSXIUa-8qUHrSbPdTvX-HVgFNo

      - name: Build and tag the Docker image
        run: docker build -t wildan121/test:${{ github.sha }} .

      - name: Push the Docker image to Docker Hub
        run: docker push wildan121/test:${{ github.sha }}

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: 103.175.217.162
          username: "mw.dev"
          password: "Sayonara121@Sayonara121"
          script: |
            ssh mw.dev@103.175.217.162 "docker stop test_container || true"
            ssh mw.dev@103.175.217.162 "docker rm test_container || true"
            ssh mw.dev@103.175.217.162 "docker pull wildan121/test:${{ github.sha }}"
            ssh mw.dev@103.175.217.162 "docker run -d --name test_container -p 80:80 wildan121/test:${{ github.sha }}"
